---
- name: Ensure lcsave paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ lcsave_uid }}"
    group: "{{ lcsave_gid }}"
  with_items:
    - "{{ lcsave_base_path }}"

- name: Ensure lcsave support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ lcsave_base_path }}/{{ item }}"
    mode: 0640
    owner: "{{ lcsave_uid }}"
    group: "{{ lcsave_gid }}"
  with_items:
    - env
    - labels

- name: Ensure lcsave container image is pulled
  community.docker.docker_image:
    name: "{{ lcsave_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ lcsave_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else lcsave_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure lcsave container network is created
  community.general.docker_network:
    name: "{{ lcsave_container_network }}"
    driver: bridge

- name: Ensure lcsave systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/lcsave.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ lcsave_identifier }}.service"
    mode: 0644
